/**
 * Single source for navigation and dashboard tool cards.
 * Sections preserve sidebar order.
 */
export const TOOL_REGISTRY = [
  {
    path: "/",
    name: "Dashboard",
    icon: "📊",
    section: "Network",
    tag: "HOME",
    desc: "Overview and quick access to all tools.",
    showInDashboard: false,
  },
  {
    path: "/upload",
    name: "Upload File",
    icon: "📤",
    section: "File Ops",
    tag: "AES-256",
    desc: "Encrypt & share with AES-256, password + expiry protected.",
    showInDashboard: true,
  },
  {
    path: "/hash",
    name: "Hash Tool",
    icon: "🔐",
    section: "File Ops",
    tag: "SHA-256",
    desc: "Generate SHA-256 fingerprints to detect tampering.",
    showInDashboard: true,
  },
  {
    path: "/integrity",
    name: "Integrity Check",
    icon: "🧪",
    section: "File Ops",
    tag: "VERIFY",
    desc: "Verify files against a known-good hash.",
    showInDashboard: true,
  },
  {
    path: "/malware",
    name: "Malware Scan",
    icon: "🛡️",
    section: "Threats",
    tag: "VT",
    desc: "Multi-engine file analysis via VirusTotal.",
    showInDashboard: true,
  },
  {
    path: "/url",
    name: "URL Scanner",
    icon: "🌐",
    section: "Threats",
    tag: "PHISHING",
    desc: "Keyword heuristics for phishing and suspicious URLs.",
    showInDashboard: true,
  },
  {
    path: "/jwt",
    name: "JWT Tool",
    icon: "🪪",
    section: "Crypto",
    tag: "JWT",
    desc: "Decode JWTs and optionally verify HS256 signatures offline.",
    showInDashboard: true,
  },
  {
    path: "/password",
    name: "Password Checker",
    icon: "🔑",
    section: "Crypto",
    tag: "STRENGTH",
    desc: "Strength evaluation based on server scoring.",
    showInDashboard: true,
  },
  {
    path: "/password-gen",
    name: "Password Generator",
    icon: "⚙️",
    section: "Crypto",
    tag: "GEN",
    desc: "Generate strong random passwords locally.",
    showInDashboard: true,
  },
  {
    path: "/base64",
    name: "Base64 Tool",
    icon: "🧬",
    section: "Crypto",
    tag: "ENCODE",
    desc: "Encode and decode Base64 strings.",
    showInDashboard: true,
  },
  {
    path: "/ioc",
    name: "IOC Extractor",
    icon: "🧷",
    section: "Blue Team",
    tag: "IOCs",
    desc: "Extract IPs, domains, URLs, and hashes from raw logs/text.",
    showInDashboard: true,
  },
  {
    path: "/ip",
    name: "IP Tracker",
    icon: "📍",
    section: "Network Tools",
    tag: "GEO",
    desc: "Geo, ASN, and reverse DNS for an IP address.",
    showInDashboard: true,
  },
  {
    path: "/whois",
    name: "WHOIS Lookup",
    icon: "🔎",
    section: "Network Tools",
    tag: "WHOIS",
    desc: "Domain registration summary (demo stub).",
    showInDashboard: true,
  },
  {
    path: "/port",
    name: "Port Scanner",
    icon: "📡",
    section: "Network Tools",
    tag: "NMAP",
    desc: "Local nmap-based port discovery.",
    showInDashboard: true,
  },
  {
    path: "/shodan",
    name: "Shodan Scanner",
    icon: "🛰️",
    section: "Network Tools",
    tag: "SHODAN",
    desc: "Host exposure data from Shodan (API key required).",
    showInDashboard: true,
  },
  {
    path: "/metadata",
    name: "File Metadata Analyzer",
    icon: "🧠",
    section: "Core Security Tools",
    tag: "FORENSICS",
    desc: "Magic-byte type detection + EXIF/PDF marker extraction.",
    showInDashboard: true,
  },
  {
    path: "/subdomains",
    name: "Subdomain Scanner",
    icon: "🔍",
    section: "Core Security Tools",
    tag: "RECON",
    desc: "DNS recon for common subdomain prefixes.",
    showInDashboard: true,
  },
  {
    path: "/encrypt",
    name: "Encryption Tool",
    icon: "🔐",
    section: "Core Security Tools",
    tag: "AES-GCM",
    desc: "AES-GCM (256-bit) encryption/decryption + Base64 utilities.",
    showInDashboard: true,
  },
  {
    path: "/headers",
    name: "HTTP Header Analyzer",
    icon: "🧾",
    section: "Core Security Tools",
    tag: "SEC-HEADERS",
    desc: "Fetch response headers and flag common security issues.",
    showInDashboard: true,
  },
  {
    path: "/history",
    name: "Scan History Dashboard",
    icon: "📊",
    section: "Core Security Tools",
    tag: "LOGS",
    desc: "Saved tool runs loaded from MongoDB history.",
    showInDashboard: true,
  },
];

const SECTION_ORDER = [
  "Network",
  "File Ops",
  "Threats",
  "Crypto",
  "Blue Team",
  "Network Tools",
  "Core Security Tools",
];

/** Sidebar: ordered sections with nav items. */
export function getSidebarMenu() {
  return SECTION_ORDER.map((section) => ({
    section,
    items: TOOL_REGISTRY.filter((t) => t.section === section).map(({ path, name, icon }) => ({
      path,
      name,
      icon,
    })),
  })).filter((group) => group.items.length > 0);
}

export const dashboardTools = TOOL_REGISTRY.filter((t) => t.showInDashboard);
